### ISSUE TITLE
Failed to load packing, micropip, pyparsing

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlite/demo#120]
## Description

In my company network, I met this error everytime at pyodide.asm.js:9.
But in my home network, everything is fine.

## Context

- JupyterLite version:0.1.0
- Operating System and version: windows 10
- Browser and version: Edge 114

If there is some requirements for network, please state clearly, so I can push IT to fix.

**Comment by MRYingLEE** [comment]
After a few tests I found the reasons:
1. The underlying cdn website is blocked.
2. *. whl files are blocked.

So far, it's not easy to change Security settings.

So, is it possible that all whl files are stored along with static HTMLs and with another extension?

Of course, dynamic importing could be another issue.

Any ideas?

**Comment by epugh** [comment]
I had the exact same problem...   So we did this: https://github.com/o19s/quepid-jupyterlite/blob/main/Dockerfile

And then, I import our whole jupyterlite environment into my application via https://github.com/o19s/quepid/blob/main/bin/setup_jupyterlite

**Comment by MRYingLEE** [comment]
@epugh Your suggestion is very helpful. 

The generated jupyter-lite-build.tgz was used with a local web server successfully.

I will test the possibility to use it on GitHub pages. So that I don't need to set up a web server.

Thanks,
