### ISSUE TITLE
Creating static html file from this repository and host it locally with apache html server

### ISSUE THREAD

**Issue by marcocaggioni** [jupyterlite/demo#124]
## Description

I apologize, I don't think this is necessarily a bug, but It may help to clarify in the docs if this is expected. I'm trying to create a jupyterlite static html site of this repo and self host with apache web server. 

## Reproduce

* Clone this repo
* Create a new conda environment python 3.10
* Install requirements.txt
* run: jupyter lite serve --contents content
* copy _output folder to server with apache
* Jupyterlite works fine but the filesystem is not synced. I see in the browser console this error.

![image](https://github.com/jupyterlite/demo/assets/5448255/5201fb27-f4d0-4cc1-8da0-8072ff9f60ad)

*There is no problem if I serve it locally with the jupyter lite serve --contents content that starts a webserver on 8000 port 

## Expected behavior

Not sure if just by copying the static content and serving with apache is enough for jupyterlite to work. looks like the only think that does not work is the synchronization of the kernel and the jupyterlab filesystem.

**Comment by jtpio** [comment]
Thanks @marcocaggioni for reporting.

> Jupyterlite works fine but the filesystem is not synced. I see in the browser console this error.

Maybe this is related to the browser you are using? https://jupyterlite.readthedocs.io/en/stable/howto/configure/advanced/service-worker.html#limitations

**Comment by marcocaggioni** [comment]
Thanks this explains the behavior, I did not realize that when not running on localhost the server needs to support https.
thanks you for your answer and for all your work!

![image](https://github.com/jupyterlite/demo/assets/5448255/2f7dbd7b-60b6-45a4-a993-b67931e55242)
