### ISSUE TITLE
Add screencast to show how to use the template

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/demo#16]
### Problem

To make it event clearier and show how to use the GitHub template.

### Suggested Improvement

There is already a screenshot in https://github.com/jupyterlite/demo#usage.

@martinRenou maybe we could update it and use the screencast from this tweet? https://twitter.com/martinRenou/status/1415683682036162567

**Comment by martinRenou** [comment]
Yes feel free to reuse it! Should I open a PR?

**Comment by jtpio** [comment]
> Should I open a PR?

if you have it around that would be great!

**Comment by martinRenou** [comment]
![cut (1)](https://user-images.githubusercontent.com/21197331/125816904-5768008a-77de-4cb3-8013-f3999b135c02.gif)

**Comment by jtpio** [comment]
Fixed by #17
