### ISSUE TITLE
Error displaying widget

### ISSUE THREAD

**Issue by giswqs** [jupyterlite/demo#18]
The ipyleaflet example stops working. It says `Error displaying widget`
https://jupyterlite.github.io/demo/lab/

**Comment by sclamons** [comment]
It's not just ipyleaflet -- the matplotlib.ipynb notebook fails in the last cell, with a "could not instantiate widget" error in the console. I'm seeing this in my own notebooks anywhere I try to call plt.plot or plt.subplot from a %matplotlib widget environment.

**Comment by angueyraNIH** [comment]
ipywidgets is also not working. Error is thrown when loading extension.
"ValueError: Can't find a pure Python 3 wheel for 'widgetsnbextension~=4.0'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels."

If widgetsnbextension wheel is dowloaded and loaded before ipywidgets, the error is not thrown but widgets do not display.
