### ISSUE TITLE
Site is broken after update to jupyterlite==0.1.0a6

### ISSUE THREAD

**Issue by voland62** [jupyterlite/demo#20]
Seems like index page broken now. It is after update to jupyterlite==0.1.0a6
With jupyterlite==0.1.0a5 it worked good.

**Comment by voland62** [comment]
Well, I'm to sure the reason, but main [demo page](https://jupyterlite.github.io/demo/lab/index.html)  is broken for now...

**Comment by jtpio** [comment]
Thanks @voland62 for reporting.

I did the update to `0.1.0a6` a while ago in a personal repo and it worked fine: https://github.com/jtpio/lit

In the dev tools console, it seems to be related to the settings:

![image](https://user-images.githubusercontent.com/591645/132227666-40a217f5-98ce-4ed5-993c-8fb413712ee4.png)

**Comment by jtpio** [comment]
This should now be fixed by #21 and #22:

![image](https://user-images.githubusercontent.com/591645/132233572-813670f1-184e-483a-a932-45ed94b18265.png)

Thanks again for reporting!

**Comment by voland62** [comment]
Thank you for the quick fix!

But, I still want to ask about workflow (I can make dedicated issue for that, but it is maybe something wrong with me: I totally confused with docs...). Correct me please if I'm getting something wrong. 
So, the workflow, as I see it:

### Let's say, I want to create **math.ipynb**, and share it with my students... So I:
   1.  Use this "demo" template, for creation my own repo with **main** branch only. (At this stage there isn't gh-pages for default notebooks yet, so no any public site where I can create my new notebook exists yet...)
   2. git clone my/new/repo to get it locally
   3.      cd my/new/repo
             mamba create -n jupyterlite
             conda activate jupyterlite
             pip install -r requirements.txt
   4.      jupyter lite build --contents content
           jupyter lite serve
         open http://127.0.0.1:8000/index.html in a browser to test it locally.
   5. So now I can create **math.ipynb**. But, as I understand it, it exists only in the brower's local storage, so to get it on my file  system, I select "Download" from menu, and save it inside /contents/ folder of my repo. I have to do this on every edit...
   6. Than I do `git add/commit/push` as always.
   7. After the push, git Actions automation launches full build on github servers, and populate gh-pages branch of my repo. (It takes 4 min, btw... )
   8. At this point I can see/work with my new **math.ipynb** online.  To save it, I need to do Dowload/commit/push cycle again.. 
   9. I'm still not able to figure out how to get "shareable llink" (menu point doesn't work), so the best I can do is to send link to my.github.io/my-repo/lab/index.html, and ask her to open **math.ipynb** from iside..

### Questions:
Is this right workflow?
We still can't save on GitHub directly from the IDE (like in Google Colab), right?
We still can't get link to notebook/cell, right?
Can a collaboration be enabled in our case?(I can't understand docs, to be honest...)

Thanks.

**Comment by jtpio** [comment]
Thanks @voland62 for the valuable feedback :+1: 

> I can make dedicated issue for that

I can provide a couple of answers to these questions, but the best would indeed be to open a new issue on the main repo for visibility: https://github.com/jupyterlite/jupyterlite

The docs are still a bit rough for now . Probably we should improve them by adding more detailed "User Guides", with step by step instructions to start from a repo and end up with a deployed website.
