### ISSUE TITLE
Settings and Actions links in readme broken

### ISSUE THREAD

**Issue by ianhi** [jupyterlite/demo#46]
### Problem
In the template section the links to Actions and Settings etc dont lead to the approriate repo tabs, rather to parts of the code that are then non-existent.

so here: 

![image](https://user-images.githubusercontent.com/10111092/150197138-af82c69b-c8bd-4f14-9d6a-a7ded4338657.png)
 the actions link leads to the non-existent https://github.com/jupyterlite/demo/blob/main/actions

### Suggested Improvement
Make these links lead to the approriate https://github.com/jupyterlite/demo/actions

**Comment by jtpio** [comment]
Thanks @ianhi for spottng this :+1: 

> Make these links lead to the appropriate https://github.com/jupyterlite/demo/actions

Sounds good. Mind opening a PR? Thanks!

**Comment by jtpio** [comment]
Closing as fixed now that the README is pointing to the docs: https://github.com/jupyterlite/demo#deploy-your-jupyterlite-website-on-github-pages
