### ISSUE TITLE
How to enable real-time collaboration

### ISSUE THREAD

**Issue by horaceg** [jupyterlite/demo#70]
### Problem

There is no section about collaboration specific to the demo. In the jupyterlite docs, it says that it should be enabled but I can't see this on my instance which is a vanilla fork of the demo.

I also tried to deploy my own from scratch, and the collaboration works on my machine but not when it is deployed on e.g. github pages nor gitlab pages.

I have tried to append `room=0`, put a specific room number in the configuration that I then put in the url, but the two open windows don't show the other modifications.

### Suggested Improvement

A section that says how to make real-time collaboration work

**Comment by jtpio** [comment]
Thanks @horaceg.

Enabling RTC is documented here: https://jupyterlite.readthedocs.io/en/latest/rtc/index.html#enabling-rtc-in-jupyterlite

So if you created your own JupyterLite website from this demo repo, you can add a new `jupyter-lite.json ` file with the `collaborative` setting to the repo.

**Comment by horaceg** [comment]
Hi @jtpio,

Thank you, it seems to work for me in private window only on my computer. I guess this is enough for me.
