### ISSUE TITLE
xeus-kernels fail

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlite/demo#80]
all xeus kernels fail with the same error as https://github.com/jupyterlite/xeus-sqlite-kernel/issues/10.

Interestingly I can locally install **all** of them via pip and they work **without** that issue

**Comment by DerThorsten** [comment]
@jtpio when I install all extensions locally (as in the requirements) I can reproduce the error locally...so...lets figure out which one is the bad one

**Comment by DerThorsten** [comment]
it sems that the xeus kernels atm dont work when ipywidgets is installed

**Comment by jtpio** [comment]
@DerThorsten the SQLite kernel seems to be working (when opening https://jupyterlite.github.io/demo/lab/index.html in a private window):

![image](https://user-images.githubusercontent.com/591645/168535648-04ce7ff9-c6e0-45a0-aef7-70b60346cd09.png)

> it sems that the xeus kernels atm dont work when ipywidgets is installed

You mean when the `ipywidgets` Python package is installed as part of the deployment? Or when the xeus kernels are compiled with widgets.

**Comment by martinRenou** [comment]
This issue is coming from xeus which complains about a non-existing comm target, and lamentably fails to show the error message. We fixed it very recently in https://github.com/jupyter-xeus/xeus/pull/327/files. Maybe we are not using that fix yet

**Comment by martinRenou** [comment]
Just to give more context about this error, https://github.com/jupyter-xeus/xeus/pull/327/files#diff-af1c39110d53dd864ae63b152634851fb7b89dbb43a93584ecd368db8414e9c2L90 is trying to concatenate an `std::string` with a `fixed_string<64>` resulting in a `fixed_string<64>` that is more than 64 characters, which makes a static assert fail.

**Comment by martinRenou** [comment]
I think the reason why you are not able to reproduce locally @DerThorsten is because you don't have the ipywidgets labextension in the page, so the front-end is not requesting the kernel for comm targets.

**Comment by martinRenou** [comment]
This should fix it https://github.com/jupyterlite/xeus-sqlite-kernel/pull/11
