### ISSUE TITLE
overrides settings of "@jupyterlab/notebook-extension:tracker" to change the rendering layout

### ISSUE THREAD

**Issue by jdeantoni** [jupyterlite/demo#96]
Hi,

I try to configure the look and feel of the resulting embedded notebook.
My (first) goal is to change the rendering layout to 'side-by-side'. Could you please explain me how to do that ?
I tried several things (overrides.json, jupyter-lite.json in different folder, etc) but with no luck.
I guess the closest thing I did is to add a jupyter-lite.json file in the root directory of my repo with the following content:
`{

    "jupyter-lite-schema-version": 0,
    "jupyter-config-data": {
      "disabledExtensions": [
        "@jupyterlab/drawio-extension",
        "jupyterlab-kernel-spy",
        "jupyterlab-tour"
      ]
    },
    "settingsOverrides": {
         "@jupyterlab/notebook-extension:tracker": {
            "renderingLayout": "side-by-side"
         },
        "@jupyterlab/apputils-extension:palette": {"modal": false}
     }
}`

the file seems considered since the disabled extensions are actually disabled but the rendering layout is not changed :-/
the repo is here: https://github.com/jdeantoni/iiwjupylite and the resulting page here: https://jdeantoni.github.io/iiwjupylite/lab/index.html

any help would be appreciated
thanks

**Comment by jtpio** [comment]
@jdeantoni have you tried putting the following in the `overrides.json` file?

```json
"@jupyterlab/notebook-extension:tracker": {
  "renderingLayout": "side-by-side"
},
"@jupyterlab/apputils-extension:palette": {"modal": false}
```

**Comment by jdeantoni** [comment]
Thanks @jtpio for the input. 
I thought I was far, but thanks to you, I found the problem.

It works with the following overrides.json file at the root of the project:
`{
   "@jupyterlab/notebook-extension:tracker": {
     "renderingLayout": "side-by-side"
   },
   "@jupyterlab/apputils-extension:palette": {"modal": false}
}`

note that enclosing brackets are mandatory !
thanks again
