### ISSUE TITLE
ipywidgets fails to install in jupyterlite/demo deployment

### ISSUE THREAD

**Issue by pierre-haessig** [jupyterlite/demo#97]
## Description

I believe ipywidgets fail to install in the Jupyterlite deployment of the jupyterlite/demo repo. It was working in late July.

This started as a discussion here: https://discourse.jupyter.org/t/miscellaneous-questions-on-the-usage-of-jupyterlite

## Reproduce

1. Open a fresh Jupyterlite demo from https://jupyterlite.github.io/demo/lab/ 
2. Create and run cell with 

```
import piplite
await piplite.install(['ipywidgets'])
```
3. It yields a `ValueError: Can't find a pure Python 3 wheel for 'widgetsnbextension~=4.0'.`

## Expected behavior

`ipywidgets` should install fine. This is the case in the official Jupyterlite demo https://jupyterlite.readthedocs.io/en/latest/_static/lab/, so there must be some divergence between the two deployments.

## Context

- JupyterLite version: Version 0.1.0-beta.12
- Operating System and version: Ubuntu 22.04
- Browser and version: Firefox 104 (as a snap from Ubuntu)

**Comment by bollwyvl** [comment]
See https://github.com/jupyterlite/jupyterlite/pull/783.

**Comment by kolibril13** [comment]
This issue is now resolved, as https://github.com/jupyterlite/jupyterlite/pull/793 is merged.  This fix can be tested in  [this](https://jupyterlite--793.org.readthedocs.build/en/793/_static/lab/index.html) JupyterLite instance from the according pull request.

As widgets are still broken in https://jupyterlite.github.io/demo/lab/ , I would like to suggest a new JupyterLite release that will fix the JupyterLite demo and all JupyterLite notebooks with ipywidgets out there.

**Comment by pierre-haessig** [comment]
> This issue is now resolved, as [jupyterlite/jupyterlite#793](https://github.com/jupyterlite/jupyterlite/pull/793) is merged. This fix can be tested in [this](https://jupyterlite--793.org.readthedocs.build/en/793/_static/lab/index.html) JupyterLite instance from the according pull request.

Nice! 

Indeed on the https://jupyterlite--793.org.readthedocs.build/en/793/_static/lab/index.html instance, running

```
import piplite
await piplite.install(['ipywidgets'])
```

does indeed installs ipywidgets 8.0.2.

And I got a minimal example working fine:

```
import ipywidgets

def f(x):
    print(x)

ipywidgets.interactive(f, x=(-1,1,0.5))
```

**Comment by jtpio** [comment]
`0.1.0b13` is out https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b13

And https://github.com/jupyterlite/demo/pull/98 updated the demo repo to the new release, which should fix this issue.

**Comment by pierre-haessig** [comment]
Thanks!
